In [2]:
pip install tensorflow


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [6]:
import tensorflow as tf


In [5]:
print(tf.__version__)

2.18.0


In [9]:

from tensorflow.keras.preprocessing.text import one_hot

In [16]:
from tensorflow.keras.preprocessing.text import one_hot

# Sample sentences (as strings, not pre-tokenized)
sentences = [
    "the cat sat on the mat",
    "the dog ate my homework"
]

vocab_size = 50  # Vocabulary size (hash space)

# Correct usage: Apply one_hot to each sentence (string)
encoded_sentences = [one_hot(sentence, vocab_size) for sentence in sentences]
print(encoded_sentences)

[[43, 11, 24, 43, 43, 19], [43, 15, 20, 45, 49]]


In [22]:
# word Embeeding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [28]:
# sentences in sent must bee of all same size

import numpy as np
sent_length=9
embedded_code=pad_sequences(encoded_sentences,padding='pre',maxlen=9)
print(embedded_code)


[[ 0  0  0 43 11 24 43 43 19]
 [ 0  0  0  0 43 15 20 45 49]]


# Feauture Dimensions from one_hot

In [32]:
dim=10
model=Sequential()

model.add(Embedding(
    input_dim=vocab_size,  # Vocabulary size
    output_dim=dim,        # Embedding dimension
    input_length=sent_length  # Length of input sequences
))

C:\Users\hp\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [33]:
model.compile('adam','mse')

In [36]:
embedded_code[0]

array([ 0,  0,  0, 43, 11, 24, 43, 43, 19])

In [35]:
print(model.predict(embedded_code))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 347ms/step
[[[-1.8797070e-04 -1.7001938e-02 -2.2568082e-02 -4.4116367e-02
   -3.3288859e-02  3.4214143e-02 -4.1839492e-02  1.6510379e-02
    2.8016161e-02  4.7306631e-02]
  [-1.8797070e-04 -1.7001938e-02 -2.2568082e-02 -4.4116367e-02
   -3.3288859e-02  3.4214143e-02 -4.1839492e-02  1.6510379e-02
    2.8016161e-02  4.7306631e-02]
  [-1.8797070e-04 -1.7001938e-02 -2.2568082e-02 -4.4116367e-02
   -3.3288859e-02  3.4214143e-02 -4.1839492e-02  1.6510379e-02
    2.8016161e-02  4.7306631e-02]
  [-2.1532550e-03 -1.8137764e-02  3.4200739e-02  3.0830018e-03
   -1.4005527e-03  4.2199258e-02  1.0063458e-02 -4.2568114e-02
    2.3568515e-02  2.0558704e-02]
  [ 4.8350763e-02  4.3576028e-02  4.1154388e-02  3.4865234e-02
    9.6127167e-03 -4.0784933e-02 -1.9799054e-02 -3.1392016e-02
    1.9408550e-02 -4.9818266e-02]
  [ 2.0287227e-02 -3.1498216e-02 -4.3458521e-02 -3.4039378e-02
   -1.6417205e-02 -7.3102228e-03  5.4282062e-03 -1.9606603e-02
    4.3130759e-02 -3.7030421e-02]
 

# completed